# Generated by Django 3.0.5 on 2020-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=50)),
                ('estado_cívil', models.CharField(max_length=200)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qtdade_filhos', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
